CREATE TABLE verbs (
	id SERIAL PRIMARY KEY,
	word VARCHAR(50) NOT NULL,
	sense VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	tense VARCHAR(50) NOT NULL,
	parent VARCHAR(50) NOT NULL,
	sound VARCHAR(50) NOT NULL,
);