CREATE TABLE worbs (
	id SERIAL PRIMARY KEY,
	word VARCHAR(50) NOT NULL,
	sense VARCHAR(50) NOT NULL,
	sound VARCHAR(50) NOT NULL,
	level VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	categories VARCHAR(50) NOT NULL,
	popularity VARCHAR(50) NOT NULL
);